{{- if .Values.ingress.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "backend.fullname" . }}-ingress
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "backend.fullname" . }}
            port: 
              number: 80
# In order for the local DNS stuff to work minikube tunnel needs to be active in a command prompt window
# then you also need to add the IP 127.0.0.1 and the host name to the windows hosts file 
{{- end }}